import Head from "next/head";
import Script from "next/script";
import Banner from "../components/Banner";
import Features from "../components/Features";
import Featured from "../components/Featured";
import Experiences from "../components/Experiences";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        id="nav"
        dangerouslySetInnerHTML={{
          __html: `const btn = document.querySelector("button.mobile-menu-button");
        const menu = document.querySelector(".mobile-menu");
        
        btn.addEventListener("click", () => {
          menu.classList.toggle("hidden");
        });`,
        }}
      />
      <Layout>
        <Banner />
        <Featured />
        <Features />
        <Experiences />
      </Layout>
    </div>
  );
}
