import Head from "next/head";
import Banner from "../components/Banner";
import Features from "../components/Features";
import Featured from "../components/Featured";
import Experiences from "../components/Experiences";
import Layout from "../components/Layout";
import { API_URL } from "@/config/index";
import Preview from "@/components/Preview";

export default function Home({ hotels }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Banner />
        <Featured hotels={hotels} />
        <Features />
        <Experiences />
      </Layout>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(`${API_URL}/api/hotels`);
  const hotels = await res.json();
  return {
    props: { hotels: hotels.slice(0, 4) },
    revalidate: 1,
  };
}
